import { z } from "zod";

const categories = ["Beach", "Mountain", "City", "Heritage", "Nature", "Adventure"] as const;

export const createDestinationSchema = z.object({
  body: z.object({
    name: z.string({ message: "Name is required" }).min(2, "Name is too short").trim(),
    city: z.string({ message: "City is required" }).min(1).trim(),
    state: z.string({ message: "State is required" }).min(1).trim(),
    country: z.string({ message: "Country is required" }).min(2, "Country is too short").trim(),
    continent: z.string({ message: "Continent is required" }).min(2).trim(),
    category: z.enum(categories, { message: "Invalid category" }),
    categories: z.array(z.string()).optional(),
    shortDescription: z.string({ message: "Short description is required" }).min(5).trim(),
    fullDescription: z.string({ message: "Full description is required" }).min(10).trim(),
    bestTimeToVisit: z.string({ message: "Best time to visit is required" }).trim(),
    averageBudget: z.number({ message: "Average budget is required" }).nonnegative(),
    averageCost: z.number().nonnegative().optional(),
    durationRecommendation: z.string({ message: "Duration recommendation is required" }).trim(),
    weatherInformation: z.string({ message: "Weather information is required" }).trim(),
    famousFor: z.string({ message: "Famous for is required" }).trim(),
    topAttractions: z.array(z.string()).min(1, "At least one attraction is required"),
    activities: z.array(z.string()).min(1, "At least one activity is required"),
    localCuisine: z.array(z.string()).min(1, "At least one local cuisine is required"),
    transportationOptions: z.array(z.string()).min(1, "At least one transportation option is required"),
    nearestAirport: z.string({ message: "Nearest airport is required" }).trim(),
    nearestRailwayStation: z.string({ message: "Nearest railway station is required" }).trim(),
    languagesSpoken: z.array(z.string()).min(1, "At least one language is required"),
    currency: z.string({ message: "Currency is required" }).trim(),
    safetyInformation: z.string({ message: "Safety information is required" }).trim(),
    travelTips: z.string({ message: "Travel tips are required" }).trim(),
    latitude: z.number({ message: "Latitude is required" }).min(-90).max(90),
    longitude: z.number({ message: "Longitude is required" }).min(-180).max(180),
    images: z.array(z.string()).min(1, "At least one image is required"),
    image: z.string().optional().or(z.string().length(0)),
    rating: z.number().min(0).max(5).optional(),
    popularPlaces: z.array(z.string()).optional(),
  }),
});

export const updateDestinationSchema = z.object({
  body: z.object({
    name: z.string().min(2).trim().optional(),
    city: z.string().min(1).trim().optional(),
    state: z.string().min(1).trim().optional(),
    country: z.string().min(2).trim().optional(),
    continent: z.string().min(2).trim().optional(),
    category: z.enum(categories).optional(),
    categories: z.array(z.string()).optional(),
    shortDescription: z.string().min(5).trim().optional(),
    fullDescription: z.string().min(10).trim().optional(),
    bestTimeToVisit: z.string().trim().optional(),
    averageBudget: z.number().nonnegative().optional(),
    averageCost: z.number().nonnegative().optional(),
    durationRecommendation: z.string().trim().optional(),
    weatherInformation: z.string().trim().optional(),
    famousFor: z.string().trim().optional(),
    topAttractions: z.array(z.string()).min(1).optional(),
    activities: z.array(z.string()).min(1).optional(),
    localCuisine: z.array(z.string()).min(1).optional(),
    transportationOptions: z.array(z.string()).min(1).optional(),
    nearestAirport: z.string().trim().optional(),
    nearestRailwayStation: z.string().trim().optional(),
    languagesSpoken: z.array(z.string()).min(1).optional(),
    currency: z.string().trim().optional(),
    safetyInformation: z.string().trim().optional(),
    travelTips: z.string().trim().optional(),
    latitude: z.number().min(-90).max(90).optional(),
    longitude: z.number().min(-180).max(180).optional(),
    images: z.array(z.string()).min(1).optional(),
    image: z.string().optional().or(z.string().length(0)),
    rating: z.number().min(0).max(5).optional(),
    popularPlaces: z.array(z.string()).optional(),
  }),
});

export const calculateRouteSchema = z.object({
  body: z.object({
    originLatitude: z.number({ message: "Origin latitude is required" }).min(-90).max(90),
    originLongitude: z.number({ message: "Origin longitude is required" }).min(-180).max(180),
    destinationId: z.string({ message: "Destination ID is required" }).regex(/^[0-9a-fA-F]{24}$/, "Invalid Destination ID format"),
    modeOfTransport: z.enum(["car", "train", "flight"], { message: "Invalid mode of transport" }),
  }),
});
