import mongoose from "mongoose";
import { Destination } from "./models/Destination";
import { Weather } from "./models/Weather";
import { logger } from "./utils/logger";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env") });

const destinationsData = [
  // --- India (10 Destinations) ---
  {
    name: "Goa",
    description: "Famous for its pristine sandy beaches, vibrant nightlife, Portuguese heritage, and delicious seafood.",
    country: "India",
    category: "Beach",
    categories: ["beach", "culture", "food", "shopping", "adventure"],
    latitude: 15.2993,
    longitude: 74.1240,
    averageCost: 45,
    activities: ["Swimming", "Sunbathing", "Water Sports", "Fort Sightseeing", "Night Clubbing"],
    bestTimeToVisit: "November - February",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2",
    popularPlaces: ["Baga Beach", "Anjuna Beach", "Aguada Fort", "Basilica of Bom Jesus"],
  },
  {
    name: "Kashmir",
    description: "Known as 'Paradise on Earth', famous for its snow-capped mountains, houseboats, beautiful gardens, and serene lakes.",
    country: "India",
    category: "Mountain",
    categories: ["mountain", "nature", "adventure", "culture"],
    latitude: 34.0837,
    longitude: 74.7973,
    averageCost: 50,
    activities: ["Shikara Riding", "Gondola Ride", "Skiing", "Sightseeing", "Houseboat Stay"],
    bestTimeToVisit: "March - October",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1566228015668-4c45dbc4e2f5",
    popularPlaces: ["Dal Lake", "Gulmarg", "Pahalgam", "Shalimar Bagh"],
  },
  {
    name: "Ladakh",
    description: "A high-altitude cold desert offering stunning landscapes, ancient Buddhist monasteries, and adventure road trips.",
    country: "India",
    category: "Adventure",
    categories: ["mountain", "adventure", "culture", "nature"],
    latitude: 34.1526,
    longitude: 77.5770,
    averageCost: 55,
    activities: ["Motorcycling", "Trekking", "Camping", "Monastery Tours", "Stargazing"],
    bestTimeToVisit: "June - September",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2",
    popularPlaces: ["Pangong Lake", "Nubra Valley", "Khardung La", "Leh Palace"],
  },
  {
    name: "Jaipur",
    description: "The 'Pink City' of India, showcasing magnificent fortresses, majestic royal palaces, and rich cultural crafts.",
    country: "India",
    category: "Heritage",
    categories: ["heritage", "culture", "shopping", "food"],
    latitude: 26.9124,
    longitude: 75.7873,
    averageCost: 40,
    activities: ["Fort Exploration", "Royal Palace Tours", "Shopping", "Puppet Shows", "Local Dining"],
    bestTimeToVisit: "October - March",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1477584322902-471a53b9d433",
    popularPlaces: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
  },
  {
    name: "Kerala",
    description: "God's Own Country, famed for its tranquil backwaters, palm-fringed canals, Ayurvedic resorts, and rich flora/fauna.",
    country: "India",
    category: "Nature",
    categories: ["nature", "beach", "culture", "food"],
    latitude: 10.8505,
    longitude: 76.2711,
    averageCost: 45,
    activities: ["Backwater Cruise", "Ayurveda Treatment", "Kathakali Watching", "Wildlife Safari"],
    bestTimeToVisit: "September - March",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2",
    popularPlaces: ["Alleppey Houseboats", "Munnar Tea Gardens", "Wayanad Forests", "Kochi Fort"],
  },
  {
    name: "Rishikesh",
    description: "The 'Yoga Capital of the World', situated on the banks of the sacred Ganges River, offering extreme adventure sports.",
    country: "India",
    category: "Adventure",
    categories: ["adventure", "culture", "nature"],
    latitude: 30.0869,
    longitude: 78.2676,
    averageCost: 35,
    activities: ["River Rafting", "Bungee Jumping", "Yoga and Meditation", "Ganga Aarti Watching", "Trekking"],
    bestTimeToVisit: "October - April",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597",
    popularPlaces: ["Lakshman Jhula", "Triveni Ghat", "Beatles Ashram", "Neer Garh Waterfall"],
  },
  {
    name: "Manali",
    description: "A rustic mountain town offering spectacular valleys, pine forests, winter snow sports, and adventure trails.",
    country: "India",
    category: "Mountain",
    categories: ["mountain", "adventure", "nature"],
    latitude: 32.2396,
    longitude: 77.1887,
    averageCost: 45,
    activities: ["Paragliding", "Solang Valley Snow Sports", "Trekking", "Rohtang Pass Tour", "Temple Visits"],
    bestTimeToVisit: "October - June",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa",
    popularPlaces: ["Solang Valley", "Rohtang Pass", "Hadimba Temple", "Jogini Waterfalls"],
  },
  {
    name: "Shimla",
    description: "The former summer capital of British India, offering colonial style architecture, pedestrian malls, and scenic ridges.",
    country: "India",
    category: "Mountain",
    categories: ["mountain", "heritage", "shopping"],
    latitude: 31.1048,
    longitude: 77.1734,
    averageCost: 45,
    activities: ["Toy Train Ride", "Ridge Walk", "Shopping on Mall Road", "Ice Skating"],
    bestTimeToVisit: "March - June",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1562670302-32dd035b1d38",
    popularPlaces: ["The Ridge", "Mall Road", "Kalka-Shimla Toy Train", "Jakhoo Temple"],
  },
  {
    name: "Andaman",
    description: "Stunning island archipelago featuring crystal clear turquoise waters, vibrant coral reefs, and dark historical monuments.",
    country: "India",
    category: "Beach",
    categories: ["beach", "adventure", "nature"],
    latitude: 11.7401,
    longitude: 92.6586,
    averageCost: 65,
    activities: ["Scuba Diving", "Snorkeling", "Glass Bottom Boat Rides", "Island Hopping", "Light & Sound Show"],
    bestTimeToVisit: "October - May",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3",
    popularPlaces: ["Radhanagar Beach", "Havelock Island", "Cellular Jail", "Neil Island"],
  },
  {
    name: "Udaipur",
    description: "The 'City of Lakes', renowned for its luxury floating palaces, historic fort walls, and breathtaking romantic vistas.",
    country: "India",
    category: "Heritage",
    categories: ["heritage", "culture", "nature"],
    latitude: 24.5854,
    longitude: 73.7125,
    averageCost: 45,
    activities: ["Boat Cruise", "Palace Tours", "Museum Exploration", "Traditional Dance Shows"],
    bestTimeToVisit: "October - March",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1595928642581-f50f4f3453a5",
    popularPlaces: ["Lake Palace", "City Palace Udaipur", "Jag Mandir", "Fateh Sagar Lake"],
  },

  // --- International (12 Destinations) ---
  {
    name: "Bali",
    description: "A tropical Indonesian island famous for its iconic forested volcanic mountains, rice paddies, beaches, and coral reefs.",
    country: "Indonesia",
    category: "Beach",
    categories: ["beach", "culture", "adventure", "nature", "food"],
    latitude: -8.4095,
    longitude: 115.1889,
    averageCost: 60,
    activities: ["Surfing", "Temple Visits", "Yoga", "Snorkeling", "Hiking Mount Batur"],
    bestTimeToVisit: "April - October",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4",
    popularPlaces: ["Ubud Monkey Forest", "Uluwatu Temple", "Tanah Lot", "Seminyak Beach"],
  },
  {
    name: "Dubai",
    description: "A global city of high luxury, futuristic skyscrapers, immense shopping malls, and sweeping desert dune safaris.",
    country: "United Arab Emirates",
    category: "City",
    categories: ["city", "shopping", "adventure", "beach", "culture"],
    latitude: 25.2048,
    longitude: 55.2708,
    averageCost: 150,
    activities: ["Burj Khalifa Observation", "Desert Dune Bashing", "Shopping", "Skydiving", "Yacht Cruises"],
    bestTimeToVisit: "November - March",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    popularPlaces: ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Marina Beach"],
  },
  {
    name: "Paris",
    description: "The global center for art, fashion, gastronomy, and culture, famed for its 19th-century cityscape and romantic landmarks.",
    country: "France",
    category: "City",
    categories: ["city", "culture", "food", "shopping", "heritage"],
    latitude: 48.8566,
    longitude: 2.3522,
    averageCost: 180,
    activities: ["Eiffel Tower Visit", "Louvre Museum Tour", "Seine River Cruise", "Cafe Lounging", "Pastry Tasting"],
    bestTimeToVisit: "April - October",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    popularPlaces: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Champs-Élysées"],
  },
  {
    name: "London",
    description: "The capital of the UK, a 21st-century city with history stretching back to Roman times. Famed for royal history and theatres.",
    country: "United Kingdom",
    category: "City",
    categories: ["city", "culture", "shopping", "heritage", "food"],
    latitude: 51.5074,
    longitude: -0.1278,
    averageCost: 190,
    activities: ["London Eye Ride", "Tower Bridge Tour", "Museum Sightseeing", "West End Musical Watching"],
    bestTimeToVisit: "May - September",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad",
    popularPlaces: ["Big Ben", "Tower of London", "British Museum", "London Eye"],
  },
  {
    name: "Tokyo",
    description: "Japan's bustling capital, mixing ultra-modern skyscrapers, neon lights, and futuristic tech with historic temples and shrines.",
    country: "Japan",
    category: "City",
    categories: ["city", "food", "shopping", "culture", "heritage"],
    latitude: 35.6762,
    longitude: 139.6503,
    averageCost: 140,
    activities: ["Anime Merch Shopping", "Robot Restaurants", "Temple Exploring", "Sushi Tasting", "Shibuya Crossing Walking"],
    bestTimeToVisit: "March - May",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
    popularPlaces: ["Shibuya Crossing", "Senso-ji Temple", "Tokyo Skytree", "Meiji Jingu Shrine"],
  },
  {
    name: "Singapore",
    description: "A wealthy city-state of futurism, famed for its massive botanical biomes, super-clean streets, and culinary hawker centers.",
    country: "Singapore",
    category: "City",
    categories: ["city", "food", "shopping", "culture", "nature"],
    latitude: 1.3521,
    longitude: 103.8198,
    averageCost: 160,
    activities: ["Night Safari", "Gardens Walking", "Universal Studios Rides", "Hawker Food Sampling"],
    bestTimeToVisit: "February - April",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd",
    popularPlaces: ["Gardens by the Bay", "Marina Bay Sands", "Sentosa Island", "Universal Studios"],
  },
  {
    name: "Maldives",
    description: "A luxury tropical destination defined by private overwater villas, shallow lagoons, and gorgeous private house reefs.",
    country: "Maldives",
    category: "Beach",
    categories: ["beach", "nature", "adventure"],
    latitude: 3.2028,
    longitude: 73.2207,
    averageCost: 250,
    activities: ["Overwater Stay", "Snorkeling with Sharks", "Spa Treatments", "Sunset Boat Trips"],
    bestTimeToVisit: "November - April",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8",
    popularPlaces: ["Male City", "Maafushi", "Banana Reef", "Ari Atoll"],
  },
  {
    name: "Switzerland",
    description: "A landlocked European nation home to soaring Alpine peaks, crystal blue lakes, ski resorts, and lush valleys.",
    country: "Switzerland",
    category: "Mountain",
    categories: ["mountain", "adventure", "nature"],
    latitude: 46.6863,
    longitude: 7.8632,
    averageCost: 220,
    activities: ["Mountain Skiing", "Alpine Hiking", "Chocolate Tasting", "Scenic Train Tours"],
    bestTimeToVisit: "December - March",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9",
    popularPlaces: ["Interlaken", "Zermatt (Matterhorn)", "Lucerne", "Jungfraujoch"],
  },
  {
    name: "Thailand",
    description: "Revered for its gold temples, ancient ruins, friendly locals, mouthwatering pad thai, and legendary party beaches.",
    country: "Thailand",
    category: "City",
    categories: ["city", "culture", "food", "shopping", "heritage"],
    latitude: 13.7563,
    longitude: 100.5018,
    averageCost: 50,
    activities: ["Grand Palace Tours", "Floating Markets Shopping", "Street Food Dining", "Thai Massages"],
    bestTimeToVisit: "November - February",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365",
    popularPlaces: ["Grand Palace Bangkok", "Wat Arun", "Chatuchak Market", "Khao San Road"],
  },
  {
    name: "Vietnam",
    description: "A Southeast Asian gem defined by dramatic coastlines, terraced green hills, French-colonial architecture, and rich history.",
    country: "Vietnam",
    category: "City",
    categories: ["city", "culture", "food", "heritage", "nature"],
    latitude: 21.0285,
    longitude: 105.8542,
    averageCost: 35,
    activities: ["Cave Exploring", "Ancient Town Walks", "Biking Rice Fields", "Coffee Sampling"],
    bestTimeToVisit: "September - April",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1509060464153-4466739f78d0",
    popularPlaces: ["Halong Bay", "Hoi An Ancient Town", "Ho Chi Minh City", "Hanoi Old Quarter"],
  },
  {
    name: "Rome",
    description: "A sprawling, global city with nearly 3,000 years of globally influential art, architecture, and ruins on display.",
    country: "Italy",
    category: "Heritage",
    categories: ["heritage", "culture", "food", "city"],
    latitude: 41.9028,
    longitude: 12.4964,
    averageCost: 130,
    activities: ["Colosseum Tour", "Vatican Museum Walk", "Tasting Gelato & Pasta", "Trevi Fountain Wishing"],
    bestTimeToVisit: "April - June",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    popularPlaces: ["Colosseum", "Vatican Museums", "Pantheon", "Trevi Fountain"],
  },
  {
    name: "Barcelona",
    description: "Spain's coastal powerhouse, boasting fantastical Antoni Gaudí architecture, sun-baked sandy beaches, and tapas culture.",
    country: "Spain",
    category: "Beach",
    categories: ["beach", "culture", "food", "shopping", "city", "heritage"],
    latitude: 41.3851,
    longitude: 2.1734,
    averageCost: 120,
    activities: ["Gaudí Architecture Tours", "Tapas Crawls", "La Rambla Walks", "Beach Sunbathing"],
    bestTimeToVisit: "May - September",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efedd",
    popularPlaces: ["Sagrada Família", "Park Güell", "La Rambla", "Barceloneta Beach"],
  },

  // --- Additional Global Travel Hubs to make 51 ---
  {
    name: "New York",
    description: "The city that never sleeps, home to Broadway, Times Square, massive parks, and historic immigrant gates.",
    country: "United States",
    category: "City",
    categories: ["city", "culture", "food", "shopping", "heritage"],
    latitude: 40.7128,
    longitude: -74.0060,
    averageCost: 220,
    activities: ["Broadway Shows", "Central Park Cycling", "Times Square Walking", "Art Galleries Visiting"],
    bestTimeToVisit: "September - November",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9",
    popularPlaces: ["Central Park", "Times Square", "Empire State Building", "Statue of Liberty"],
  },
  {
    name: "Sydney",
    description: "Australia's largest metropolis, defined by its massive harbor bridge, architectural Opera House, and coastal surf trails.",
    country: "Australia",
    category: "City",
    categories: ["city", "beach", "culture", "food"],
    latitude: -33.8688,
    longitude: 151.2093,
    averageCost: 170,
    activities: ["Harbour Bridge Climbing", "Coogee Beach Coastal Walking", "Opera House Touring", "Ferry Riding"],
    bestTimeToVisit: "December - February",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9",
    popularPlaces: ["Sydney Opera House", "Darling Harbour", "Bondi Beach", "Sydney Harbour Bridge"],
  },
  {
    name: "Cairo",
    description: "Egypt's capital, built on the historic banks of the Nile, famous for the colossal ancient pyramids and sphinx.",
    country: "Egypt",
    category: "Heritage",
    categories: ["heritage", "culture", "food"],
    latitude: 30.0444,
    longitude: 31.2357,
    averageCost: 40,
    activities: ["Pyramids Camel Riding", "Museum Exploring", "Nile River Felucca Cruising", "Bazaar Shopping"],
    bestTimeToVisit: "October - April",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a",
    popularPlaces: ["Giza Pyramids", "Egyptian Museum", "Khan el-Khalili Bazaar", "Salah Al-Din Citadel"],
  },
  {
    name: "Cape Town",
    description: "A scenic harbor city flanked by flat-topped Table Mountain, historic vineyards, and colonies of wild penguins.",
    country: "South Africa",
    category: "Nature",
    categories: ["nature", "beach", "adventure", "culture"],
    latitude: -33.9249,
    longitude: 18.4241,
    averageCost: 80,
    activities: ["Table Mountain Cableway Ride", "Wine Tasting", "Penguin Watching", "Cape Point Driving"],
    bestTimeToVisit: "November - March",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f",
    popularPlaces: ["Table Mountain", "Boulders Beach", "Robben Island", "V&A Waterfront"],
  },
  {
    name: "Rio de Janeiro",
    description: "Famous for Copacabana beaches, the gigantic Christ the Redeemer statue on Corcovado, and wild carnival events.",
    country: "Brazil",
    category: "Beach",
    categories: ["beach", "culture", "adventure", "nature"],
    latitude: -22.9068,
    longitude: -43.1729,
    averageCost: 90,
    activities: ["Sugarloaf Mountain Cable Ride", "Samba dancing", "Hang gliding", "Beach sunbathing"],
    bestTimeToVisit: "December - March",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325",
    popularPlaces: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Ipanema Beach"],
  },
  {
    name: "Istanbul",
    description: "A cultural crossroads bridging Europe and Asia across the Bosporus Strait, boasting immense Byzantine and Ottoman structures.",
    country: "Turkey",
    category: "Heritage",
    categories: ["heritage", "culture", "food", "shopping", "city"],
    latitude: 41.0082,
    longitude: 28.9784,
    averageCost: 75,
    activities: ["Mosque Visiting", "Bosphorus Strait Cruising", "Bazaar Bargaining", "Turkish Bath Experiencing"],
    bestTimeToVisit: "April - June",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200",
    popularPlaces: ["Hagia Sophia", "Blue Mosque", "Topkapi Palace", "Grand Bazaar"],
  },
  {
    name: "Amsterdam",
    description: "Capital of the Netherlands, famous for its artistic heritage, elaborate canal systems, and narrow historic homes.",
    country: "Netherlands",
    category: "City",
    categories: ["city", "culture", "heritage", "food"],
    latitude: 52.3676,
    longitude: 4.9041,
    averageCost: 160,
    activities: ["Canal Boat Riding", "Bicycle Cruising", "Art Museum Touring", "Parks Relaxing"],
    bestTimeToVisit: "April - September",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1512470804736-2498157c2c95",
    popularPlaces: ["Van Gogh Museum", "Anne Frank House", "Rijksmuseum", "Jordaan Canals"],
  },
  {
    name: "Prague",
    description: "Capital of the Czech Republic, nicknamed the 'City of a Hundred Spires', known for its Old Town Square and Gothic structures.",
    country: "Czech Republic",
    category: "Heritage",
    categories: ["heritage", "culture", "food", "city"],
    latitude: 50.0755,
    longitude: 14.4378,
    averageCost: 85,
    activities: ["Castle Exploring", "Charles Bridge Walking", "Local Beer Tasting", "Astronomical Clock Watching"],
    bestTimeToVisit: "May - September",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf",
    popularPlaces: ["Charles Bridge", "Prague Castle", "Old Town Square", "St. Vitus Cathedral"],
  },
  {
    name: "Machu Picchu",
    description: "An Incan citadel set high in the Andes Mountains of Peru, renowned for its giant dry-stone walls and astronomical alignment.",
    country: "Peru",
    category: "Heritage",
    categories: ["heritage", "adventure", "nature"],
    latitude: -13.1631,
    longitude: -72.5450,
    averageCost: 95,
    activities: ["Inca Trail Hiking", "Ancient Ruin Tours", "Llama Spotting", "Scenic Train Riding"],
    bestTimeToVisit: "May - October",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1508962914676-134849a727f0",
    popularPlaces: ["Intihuatana", "Temple of the Sun", "Huayna Picchu", "Sacred Plaza"],
  },
  {
    name: "Agra",
    description: "Home of the monumental Taj Mahal, showcasing prime Mughal architecture and design monuments.",
    country: "India",
    category: "Heritage",
    categories: ["heritage", "culture"],
    latitude: 27.1767,
    longitude: 78.0081,
    averageCost: 35,
    activities: ["Taj Mahal Sunrise Visit", "Agra Fort Exploring", "Marble Inlay Shopping", "Eating Petha"],
    bestTimeToVisit: "October - March",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523",
    popularPlaces: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Itimad-ud-Daulah"],
  },
  {
    name: "Hampi",
    description: "A UNESCO Heritage site featuring the scattered, giant boulder ruins of the historic Vijayanagara Empire.",
    country: "India",
    category: "Heritage",
    categories: ["heritage", "culture", "adventure"],
    latitude: 15.3350,
    longitude: 76.4600,
    averageCost: 30,
    activities: ["Boulder Climbing", "Temple Touring", "Coracle River Crossing", "Sunset Watching"],
    bestTimeToVisit: "October - March",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1600100397608-f010f4ccfa0e",
    popularPlaces: ["Virupaksha Temple", "Vittala Temple Stone Chariot", "Hemakuta Hill", "Lotus Mahal"],
  },
  {
    name: "Varanasi",
    description: "One of the oldest continuously inhabited cities globally, sacred to Hindus for its river banks and spiritual rituals.",
    country: "India",
    category: "Heritage",
    categories: ["heritage", "culture", "food"],
    latitude: 25.3176,
    longitude: 82.9739,
    averageCost: 25,
    activities: ["Sunrise Boat Ride", "Ganga Aarti Experiencing", "Temple Exploring", "Saree Weaving Observing"],
    bestTimeToVisit: "October - March",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1561361531-99522c36d399",
    popularPlaces: ["Kashi Vishwanath Temple", "Dashashwamedh Ghat", "Sarnath", "Assi Ghat"],
  },
  {
    name: "Jaisalmer",
    description: "The 'Golden City', rising from the heart of the Thar Desert, showcasing ornate sandstone havelis.",
    country: "India",
    category: "Heritage",
    categories: ["heritage", "culture", "adventure"],
    latitude: 26.9157,
    longitude: 70.9083,
    averageCost: 40,
    activities: ["Desert Camping", "Camel Dune Safaris", "Fort Exploring", "Haveli Architecture Tours"],
    bestTimeToVisit: "October - March",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1590050752117-238cb061295a",
    popularPlaces: ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli", "Gadisar Lake"],
  },
  {
    name: "Munnar",
    description: "A tranquil hill station nestled in Kerala's mountains, famous for tea plantations and winding hiking roads.",
    country: "India",
    category: "Nature",
    categories: ["mountain", "nature", "culture"],
    latitude: 10.0889,
    longitude: 77.0595,
    averageCost: 40,
    activities: ["Tea Garden Walking", "Museum Visiting", "Peak Hiking", "Waterfall Snapping"],
    bestTimeToVisit: "September - May",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1508873699372-7aeab60b44ab",
    popularPlaces: ["Eravikulam National Park", "Mattupetty Dam", "Anamudi Peak", "Tea Museum"],
  },
  {
    name: "Coorg",
    description: "The 'Scotland of India', known for its lush coffee estates, mist-laden peaks, and cascading waterfalls.",
    country: "India",
    category: "Nature",
    categories: ["nature", "mountain", "adventure"],
    latitude: 12.3375,
    longitude: 75.8069,
    averageCost: 45,
    activities: ["Coffee Plantation Tours", "Elephant Interaction", "Trekking", "River Rafting"],
    bestTimeToVisit: "October - April",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1582236353982-f3f2d2424dfd",
    popularPlaces: ["Abbey Falls", "Dubare Elephant Camp", "Raja's Seat", "Namdroling Monastery"],
  },
  {
    name: "Darjeeling",
    description: "Famed globally for black tea crops and jaw-dropping mountain views of Mount Kanchenjunga.",
    country: "India",
    category: "Mountain",
    categories: ["mountain", "nature", "culture"],
    latitude: 27.0410,
    longitude: 88.2627,
    averageCost: 40,
    activities: ["Sunrise at Tiger Hill", "Toy Train Riding", "Tea Estate Touring", "Buddhist Monastery Visiting"],
    bestTimeToVisit: "March - May",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa",
    popularPlaces: ["Tiger Hill", "Batasia Loop", "Ghoom Monastery", "Padmaja Naidu Himalayan Zoo"],
  },
  {
    name: "Ooty",
    description: "A classic Nilgiri hill station famous for botanical gardens, tea estates, and historic toy trains.",
    country: "India",
    category: "Mountain",
    categories: ["mountain", "nature"],
    latitude: 11.4102,
    longitude: 76.6950,
    averageCost: 40,
    activities: ["Toy Train Riding", "Lake Boating", "Botanical Garden Walking", "Doddabetta Peak Climbing"],
    bestTimeToVisit: "October - June",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1582035341675-998db4c5b169",
    popularPlaces: ["Ooty Lake", "Botanical Gardens Ooty", "Doddabetta Peak", "Rose Garden"],
  },
  {
    name: "Kyoto",
    description: "Japan's ancient capital, famed for thousands of classical Buddhist temples, gardens, imperial palaces, and shinto shrines.",
    country: "Japan",
    category: "Heritage",
    categories: ["heritage", "culture", "nature", "food"],
    latitude: 35.0116,
    longitude: 135.7681,
    averageCost: 110,
    activities: ["Bamboo Forest Walking", "Torii Gate Hiking", "Traditional Tea Ceremonies", "Geisha Spotting"],
    bestTimeToVisit: "October - November",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
    popularPlaces: ["Fushimi Inari-taisha", "Kinkaku-ji (Golden Pavilion)", "Arashiyama Bamboo Grove", "Gion District"],
  },
  {
    name: "Seoul",
    description: "Capital of South Korea, where modern skyscrapers and high tech meet ancient palaces and street food stalls.",
    country: "South Korea",
    category: "City",
    categories: ["city", "culture", "food", "shopping", "heritage"],
    latitude: 37.5665,
    longitude: 126.9780,
    averageCost: 95,
    activities: ["Palace Touring", "K-Beauty Shopping", "Namsan Tower Ascending", "Street Food Grazing"],
    bestTimeToVisit: "September - November",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc",
    popularPlaces: ["Gyeongbokgung Palace", "Myeongdong", "N Seoul Tower", "Bukchon Hanok Village"],
  },
  {
    name: "Hong Kong",
    description: "A vertical coastal metropolis renowned for its Victoria Harbour skyline, shopping districts, and dim sum.",
    country: "Hong Kong",
    category: "City",
    categories: ["city", "food", "shopping", "culture"],
    latitude: 22.3193,
    longitude: 114.1694,
    averageCost: 150,
    activities: ["Peak Tram Riding", "Night Market Bargaining", "Dim Sum Eating", "Star Ferry Cruising"],
    bestTimeToVisit: "October - December",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1507984211203-76701d7bb120",
    popularPlaces: ["Victoria Peak", "Tian Tan Buddha", "Lantau Island", "Temple Street Night Market"],
  },
  {
    name: "Venice",
    description: "A northern Italian city built on over 100 small islands, featuring winding canals and Gothic palaces.",
    country: "Italy",
    category: "Heritage",
    categories: ["heritage", "culture", "food", "city"],
    latitude: 45.4408,
    longitude: 12.3155,
    averageCost: 170,
    activities: ["Gondola Cruising", "St. Mark's Basilica Touring", "Bridge of Sighs Snapping", "Cicchetti Tasting"],
    bestTimeToVisit: "April - October",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60",
    popularPlaces: ["St. Mark's Square", "Grand Canal", "Rialto Bridge", "Doge's Palace"],
  },
  {
    name: "Santorini",
    description: "Greece's dramatic island powerhouse, defined by volcanic cliffs, white-washed buildings, and blue domes.",
    country: "Greece",
    category: "Beach",
    categories: ["beach", "culture", "food", "nature"],
    latitude: 36.3932,
    longitude: 25.4615,
    averageCost: 200,
    activities: ["Sunset Watching in Oia", "Volcano Touring", "Black Sand Sunbathing", "Wine Tasting"],
    bestTimeToVisit: "May - October",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077",
    popularPlaces: ["Oia Village", "Fira", "Red Beach", "Akrotiri Archaeological Site"],
  },
  {
    name: "Maui",
    description: "An iconic Hawaiian island defined by golden beaches, the scenic Road to Hana, and humpback whale migrations.",
    country: "United States",
    category: "Beach",
    categories: ["beach", "adventure", "nature"],
    latitude: 20.7984,
    longitude: -156.3319,
    averageCost: 240,
    activities: ["Road to Hana Driving", "Snorkeling at Molokini", "Luau Experiencing", "Sunrise Watching on Haleakala"],
    bestTimeToVisit: "April - November",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1505852673536-d861c7ae917b",
    popularPlaces: ["Haleakala National Park", "Road to Hana", "Molokini Crater", "Kaanapali Beach"],
  },
  {
    name: "Reykjavik",
    description: "Iceland's capital, a coastal hub defined by geothermal pools, dramatic vulcanology, and northern lights.",
    country: "Iceland",
    category: "Nature",
    categories: ["nature", "adventure", "culture"],
    latitude: 64.1466,
    longitude: -21.9426,
    averageCost: 210,
    activities: ["Northern Lights Watching", "Blue Lagoon Bathing", "Waterfall Hiking", "Glacier Walking"],
    bestTimeToVisit: "September - April",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1504829857797-ddff28127792",
    popularPlaces: ["Hallgrimskirkja", "Blue Lagoon", "Golden Circle", "Harpa Concert Hall"],
  },
  {
    name: "Queenstown",
    description: "New Zealand's adventure capital, offering bungee jumps, jetboat runs, skydiving, and mountain skiing.",
    country: "New Zealand",
    category: "Adventure",
    categories: ["adventure", "mountain", "nature"],
    latitude: -45.0312,
    longitude: 168.6626,
    averageCost: 160,
    activities: ["Bungee Jumping", "Shotover Jet Riding", "Skydiving", "Milford Sound Day Trips"],
    bestTimeToVisit: "December - February",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    popularPlaces: ["Milford Sound", "Coronet Peak", "Lake Wakatipu", "Skyline Gondola"],
  },
  {
    name: "Banff",
    description: "A scenic resort town inside Alberta's national park, boasting turquoise lakes, mountains, and wildlife.",
    country: "Canada",
    category: "Mountain",
    categories: ["mountain", "nature", "adventure"],
    latitude: 51.1784,
    longitude: -115.5708,
    averageCost: 150,
    activities: ["Lake Canoeing", "Gondola Riding", "Hot Springs Bathing", "Wildlife Watching"],
    bestTimeToVisit: "June - September",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    popularPlaces: ["Lake Louise", "Moraine Lake", "Banff Gondola", "Johnston Canyon"],
  },
  {
    name: "Petra",
    description: "Jordan's ancient rose-red city, carved directly into canyon sandstone walls by Nabataeans.",
    country: "Jordan",
    category: "Heritage",
    categories: ["heritage", "adventure", "culture"],
    latitude: 30.3285,
    longitude: 35.4444,
    averageCost: 90,
    activities: ["Treasury Viewing", "Canyon Hiking", "Petra by Night Exploring", "Monastery Climbing"],
    bestTimeToVisit: "March - May",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b",
    popularPlaces: ["The Treasury (Al-Khazneh)", "The Monastery (Ad Deir)", "The Siq", "Royal Tombs"],
  },
  {
    name: "Phuket",
    description: "Thailand's largest resort island, famous for party nightlife, luxury spas, and sandy beaches.",
    country: "Thailand",
    category: "Beach",
    categories: ["beach", "adventure", "food", "shopping"],
    latitude: 7.8804,
    longitude: 98.3922,
    averageCost: 55,
    activities: ["Island Boat Tours", "Patong Nightlife Party", "Scuba Diving", "Big Buddha Visiting"],
    bestTimeToVisit: "November - April",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3",
    popularPlaces: ["Patong Beach", "Phi Phi Islands", "Big Buddha Phuket", "Kata Noi Beach"],
  },
  {
    name: "Siem Reap",
    description: "The gateway to Angkor Wat, the legendary sprawling temple complex built by the Khmer Empire.",
    country: "Cambodia",
    category: "Heritage",
    categories: ["heritage", "culture", "adventure"],
    latitude: 13.3633,
    longitude: 103.8564,
    averageCost: 35,
    activities: ["Angkor Wat Sunrise Visit", "Floating Village Boating", "Pub Street Exploring", "Tuk-Tuk Riding"],
    bestTimeToVisit: "December - February",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
    popularPlaces: ["Angkor Wat", "Bayon Temple", "Ta Prohm (Tomb Raider Temple)", "Tonle Sap Lake"],
  }
];

export async function seed(isAutoSeed = false) {
  try {
    if (!isAutoSeed) {
      const mongodbUri = process.env.MONGODB_URI;
      if (!mongodbUri) {
        logger.error("MONGODB_URI is not set in environment!");
        process.exit(1);
      }
      logger.info("Connecting to MongoDB for seeding...");
      await mongoose.connect(mongodbUri);
      logger.info("Connected to MongoDB.");
    }

    // 1. Clear existing collections
    logger.info("Clearing Destination and Weather collections...");
    await Destination.deleteMany({});
    await Weather.deleteMany({});
    logger.info("Collections cleared.");

    // 2. Insert destinations
    logger.info(`Inserting ${destinationsData.length} destination records...`);
    const seededDestinations = await Destination.insertMany(destinationsData);
    logger.info("Destinations successfully seeded.");

    // 3. Generate and insert weather caches for each destination
    logger.info("Generating weather forecasts for destinations...");
    const weatherRecords = seededDestinations.map((dest) => {
      // Mock base temp and forecast
      let baseTemp = 25;
      let conditions = ["Sunny", "Partly Cloudy", "Clear"];
      let humidity = 60;
      let windSpeed = 10;

      const cat = dest.category.toLowerCase();
      const country = dest.country.toLowerCase();

      if (cat === "mountain" || country === "switzerland") {
        baseTemp = 6;
        conditions = ["Snowy", "Foggy", "Overcast"];
        humidity = 80;
        windSpeed = 20;
      } else if (cat === "beach" || dest.name.toLowerCase() === "maldives") {
        baseTemp = 32;
        conditions = ["Sunny", "Breezy", "Clear"];
        humidity = 78;
        windSpeed = 14;
      } else if (cat === "heritage" && (country === "india" || country === "egypt")) {
        baseTemp = 36;
        conditions = ["Sunny", "Hot", "Clear"];
        humidity = 35;
        windSpeed = 8;
      } else if (country === "united kingdom") {
        baseTemp = 13;
        conditions = ["Rainy", "Drizzle", "Cloudy"];
        humidity = 90;
        windSpeed = 16;
      }

      const forecast = [];
      const today = new Date();
      for (let i = 1; i <= 5; i++) {
        const nextDate = new Date(today);
        nextDate.setDate(today.getDate() + i);
        forecast.push({
          date: nextDate.toISOString().split("T")[0],
          temperature: baseTemp + (Math.floor(Math.random() * 5) - 2),
          condition: conditions[Math.floor(Math.random() * conditions.length)],
        });
      }

      return {
        destinationName: dest.name.toLowerCase(),
        temperature: baseTemp,
        condition: conditions[0],
        humidity,
        windSpeed,
        forecast,
        lastUpdated: new Date(),
      };
    });

    logger.info(`Inserting ${weatherRecords.length} weather cache records...`);
    await Weather.insertMany(weatherRecords);
    logger.info("Weather cache successfully seeded.");

    logger.info("=== SEEDING COMPLETED SUCCESSFULY ===");
    if (!isAutoSeed) {
      process.exit(0);
    }
  } catch (error) {
    logger.error("Error seeding the database:", error);
    if (!isAutoSeed) {
      process.exit(1);
    }
  }
}

if (process.argv[1] && (process.argv[1].endsWith("seed.ts") || process.argv[1].endsWith("seed"))) {
  seed();
}
